/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Upload as PrismaUpload } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class UploadServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.UploadCountArgs, "select">): Promise<number> {
    return this.prisma.upload.count(args);
  }

  async uploads<T extends Prisma.UploadFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadFindManyArgs>
  ): Promise<PrismaUpload[]> {
    return this.prisma.upload.findMany<Prisma.UploadFindManyArgs>(args);
  }
  async upload<T extends Prisma.UploadFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadFindUniqueArgs>
  ): Promise<PrismaUpload | null> {
    return this.prisma.upload.findUnique(args);
  }
  async createUpload<T extends Prisma.UploadCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadCreateArgs>
  ): Promise<PrismaUpload> {
    return this.prisma.upload.create<T>(args);
  }
  async updateUpload<T extends Prisma.UploadUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadUpdateArgs>
  ): Promise<PrismaUpload> {
    return this.prisma.upload.update<T>(args);
  }
  async deleteUpload<T extends Prisma.UploadDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadDeleteArgs>
  ): Promise<PrismaUpload> {
    return this.prisma.upload.delete(args);
  }

  async uploadFile<T extends Prisma.UploadFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaUpload> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "file";
    const file = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.upload.update({
      where: args.where,

      data: {
        file: file as InputJsonValue,
      },
    });
  }

  async downloadFile<T extends Prisma.UploadFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadFindUniqueArgs>
  ): Promise<FileDownload> {
    const { file } = await this.prisma.upload.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      file as unknown as LocalStorageFile
    );
  }

  async deleteFile<T extends Prisma.UploadFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UploadFindUniqueArgs>
  ): Promise<PrismaUpload> {
    const { file } = await this.prisma.upload.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      file as unknown as LocalStorageFile
    );

    return await this.prisma.upload.update({
      where: args.where,

      data: {
        file: Prisma.DbNull,
      },
    });
  }
}
